"""Updated KYCSession with FK and validation

Revision ID: ade44aa1e5f4
Revises: 54b6df020207
Create Date: 2025-09-04 16:46:25.908604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade44aa1e5f4'
down_revision = '54b6df020207'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('kyc_sessions', schema=None) as batch_op:
        # 1. Add nullable user_id first
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    
    # 2. Populate with a fallback user (create this user manually if needed)
    op.execute("UPDATE kyc_sessions SET user_id = 1 WHERE user_id IS NULL")

    with op.batch_alter_table('kyc_sessions', schema=None) as batch_op:
        # 3. Now make it non-nullable
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('kyc_submission', schema=None) as batch_op:
        batch_op.alter_column('income_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kyc_submission', schema=None) as batch_op:
        batch_op.alter_column('income_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('kyc_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
